/*
  This module and parent folder was generated by `cargo`

  > cargo new --lib cargo_lib
  > tree cargo_lib
    cargo_lib
    ├── Cargo.toml
    └── src
        └── lib.rs

 */
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
